FROM openjdk:17-jdk-slim

# 소스 코드 복사
COPY . .

# 배치모듈의 빌드
RUN ./module-batch/gradlew :module-batch:build -x test --no-daemon

# 환경변수파일 복사
RUN cp src/main/resources/application.properties application.properties

# 배치모듈 JAR 파일 복사 (빌드 후 생성된 JAR 파일을 컨테이너 내로 복사)
RUN cp module-batch/build/libs/*.jar app.jar

# wait-for-it.sh 스크립트에 실행 권한 부여
RUN chmod +x /wait-for-it.sh

# RDS 엔드포인트
ENV RDS_ENDPOINT=${RDS_ENDPOINT}

# DB 서비스가 시작될 때까지 대기 후 애플리케이션 실행
ENTRYPOINT ["/wait-for-it.sh", "$RDS_ENDPOINT:3306", "--", "java", "-Dspring.config.location=file:application.properties",  "-jar", "app.jar"]
